server:
  port: 8080
  servlet:
    context-path: /network
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/luan_van_tot_nghiep"
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          socketFactory:
            fallback: true
  config:
    import: optional:file:./config/cloudinary.properties

# Cloudinary Configuration
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:your_cloud_name}
  api_key: ${CLOUDINARY_API_KEY:your_api_key}
  api_secret: ${CLOUDINARY_API_SECRET:your_api_secret}