server:
  port: 8080
  servlet:
    context-path: /network

spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:mysql://localhost:3306/luan_van_tot_nghiep"
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com  # Thay bằng email của bạn
    password: your-app-password     # Thay bằng mật khẩu ứng dụng (không phải mật khẩu đăng nhập)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          socketFactory:
            fallback: true